-- Remote equivalents for the local recovery check-in and My Day records.
-- Apply this migration before importing local demo data.
alter table public.daily_checkins
  add column if not exists wellness jsonb;

create table if not exists public.day_plans (
  day_plan_id bigint generated by default as identity primary key,
  trainee_id uuid not null references public.profiles (id) on delete cascade,
  plan_date date not null,
  available_minutes smallint not null check (available_minutes between 0 and 180),
  school_load text not null check (school_load in ('light', 'normal', 'heavy')),
  energy text not null check (energy in ('ready', 'tired', 'pain')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (trainee_id, plan_date)
);

create index if not exists day_plans_trainee_date_idx on public.day_plans (trainee_id, plan_date);

drop trigger if exists day_plans_set_updated_at on public.day_plans;
create trigger day_plans_set_updated_at before update on public.day_plans
  for each row execute function private.set_updated_at();

grant select, insert, update, delete on public.day_plans to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.day_plans enable row level security;
drop policy if exists day_plans_select_own_or_coach on public.day_plans;
create policy day_plans_select_own_or_coach on public.day_plans
  for select to authenticated
  using (trainee_id = auth.uid() or private.is_active_coach_for(trainee_id));

drop policy if exists day_plans_insert_own on public.day_plans;
create policy day_plans_insert_own on public.day_plans
  for insert to authenticated
  with check (trainee_id = auth.uid());

drop policy if exists day_plans_update_own_draft on public.day_plans;
create policy day_plans_update_own_draft on public.day_plans
  for update to authenticated
  using (trainee_id = auth.uid() and not exists (
    select 1 from public.daily_checkins c
    where c.trainee_id = day_plans.trainee_id
      and c.checkin_date = day_plans.plan_date
      and c.status <> 'draft'
  ))
  with check (trainee_id = auth.uid());

drop policy if exists day_plans_delete_own_draft on public.day_plans;
create policy day_plans_delete_own_draft on public.day_plans
  for delete to authenticated
  using (trainee_id = auth.uid());

-- Keep daily wellness private to the trainee and the active coach relationship.
drop policy if exists daily_checkins_update_own_draft on public.daily_checkins;
create policy daily_checkins_update_own_draft on public.daily_checkins
  for update to authenticated
  using (trainee_id = auth.uid() and status = 'draft')
  with check (trainee_id = auth.uid());
