-- Pro-fit MVP schema derived from the user-provided DBML attachment (remote version 20260812075500).
-- Optional structural optimizations are intentionally excluded from this migration.

create schema if not exists private;

create type public.user_role as enum ('trainee', 'coach');
create type public.user_status as enum ('active', 'disabled');
create type public.coach_trainee_status as enum ('active', 'ended');
create type public.plan_status as enum ('draft', 'published', 'archived');
create type public.daily_checkin_status as enum ('draft', 'submitted', 'reviewed');
create type public.workout_result_status as enum ('in_progress', 'completed', 'skipped');
create type public.meal_type as enum ('breakfast', 'lunch', 'dinner', 'snack');
create type public.weight_unit as enum ('kg', 'lb');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name varchar(80) not null,
  role public.user_role not null default 'trainee',
  avatar_path text,
  status public.user_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coach_trainees (
  coach_trainee_id bigint generated by default as identity primary key,
  coach_id uuid not null references public.profiles (id),
  trainee_id uuid not null references public.profiles (id),
  status public.coach_trainee_status not null default 'active',
  is_primary boolean not null default true,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create unique index coach_trainees_coach_trainee_uidx
  on public.coach_trainees (coach_id, trainee_id);
create index coach_trainees_coach_status_idx
  on public.coach_trainees (coach_id, status);
create index coach_trainees_trainee_status_idx
  on public.coach_trainees (trainee_id, status);

create table public.exercises (
  exercise_id bigint generated by default as identity primary key,
  exercise_name varchar(120) not null,
  description text,
  equipment varchar(120),
  video_url text,
  created_by uuid not null references public.profiles (id),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index exercises_created_by_idx on public.exercises (created_by);
create index exercises_exercise_name_idx on public.exercises (exercise_name);

create table public.workout_plans (
  workout_plan_id bigint generated by default as identity primary key,
  coach_id uuid not null references public.profiles (id),
  trainee_id uuid not null references public.profiles (id),
  plan_name varchar(150) not null,
  goal varchar(150),
  coach_notes text,
  start_date date not null,
  end_date date not null,
  status public.plan_status not null default 'draft',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index workout_plans_coach_id_idx on public.workout_plans (coach_id);
create index workout_plans_trainee_status_start_idx
  on public.workout_plans (trainee_id, status, start_date);

create table public.workout_days (
  workout_day_id bigint generated by default as identity primary key,
  workout_plan_id bigint not null references public.workout_plans (workout_plan_id),
  scheduled_date date not null,
  day_number smallint,
  title varchar(150) not null,
  estimated_duration_minutes smallint,
  sort_order smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index workout_days_plan_date_uidx
  on public.workout_days (workout_plan_id, scheduled_date);
create index workout_days_scheduled_date_idx on public.workout_days (scheduled_date);

create table public.workout_items (
  workout_item_id bigint generated by default as identity primary key,
  workout_day_id bigint not null references public.workout_days (workout_day_id),
  exercise_id bigint not null references public.exercises (exercise_id),
  sort_order smallint not null,
  sets smallint not null,
  reps_min smallint,
  reps_max smallint,
  target_weight numeric(8,2),
  weight_unit public.weight_unit,
  duration_seconds integer,
  rest_seconds integer,
  instructions text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index workout_items_day_sort_uidx
  on public.workout_items (workout_day_id, sort_order);
create index workout_items_exercise_id_idx on public.workout_items (exercise_id);

create table public.diet_plans (
  diet_plan_id bigint generated by default as identity primary key,
  coach_id uuid not null references public.profiles (id),
  trainee_id uuid not null references public.profiles (id),
  scheduled_date date not null,
  target_calories integer,
  target_protein_g numeric(8,2),
  target_carbs_g numeric(8,2),
  target_fat_g numeric(8,2),
  coach_notes text,
  status public.plan_status not null default 'draft',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index diet_plans_trainee_date_uidx
  on public.diet_plans (trainee_id, scheduled_date);
create index diet_plans_coach_date_idx
  on public.diet_plans (coach_id, scheduled_date);
create index diet_plans_trainee_status_date_idx
  on public.diet_plans (trainee_id, status, scheduled_date);

create table public.diet_meals (
  diet_meal_id bigint generated by default as identity primary key,
  diet_plan_id bigint not null references public.diet_plans (diet_plan_id),
  meal_type public.meal_type not null,
  meal_name varchar(120),
  meal_details text,
  sort_order smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index diet_meals_plan_type_sort_uidx
  on public.diet_meals (diet_plan_id, meal_type, sort_order);

create table public.daily_checkins (
  daily_checkin_id bigint generated by default as identity primary key,
  trainee_id uuid not null references public.profiles (id),
  checkin_date date not null,
  status public.daily_checkin_status not null default 'draft',
  trainee_notes text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index daily_checkins_trainee_date_uidx
  on public.daily_checkins (trainee_id, checkin_date);
create index daily_checkins_trainee_status_date_idx
  on public.daily_checkins (trainee_id, status, checkin_date);

create table public.workout_checkins (
  workout_checkin_id bigint generated by default as identity primary key,
  daily_checkin_id bigint not null references public.daily_checkins (daily_checkin_id),
  workout_day_id bigint not null references public.workout_days (workout_day_id),
  status public.workout_result_status not null,
  actual_duration_minutes smallint,
  trainee_notes text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index workout_checkins_daily_day_uidx
  on public.workout_checkins (daily_checkin_id, workout_day_id);
create index workout_checkins_workout_day_idx
  on public.workout_checkins (workout_day_id);
create index workout_checkins_status_idx on public.workout_checkins (status);

create table public.diet_logs (
  diet_log_id bigint generated by default as identity primary key,
  daily_checkin_id bigint not null references public.daily_checkins (daily_checkin_id),
  diet_meal_id bigint references public.diet_meals (diet_meal_id),
  meal_type public.meal_type not null,
  actual_food text,
  actual_calories integer,
  actual_protein_g numeric(8,2),
  actual_carbs_g numeric(8,2),
  actual_fat_g numeric(8,2),
  photo_path text,
  logged_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index diet_logs_daily_checkin_idx on public.diet_logs (daily_checkin_id);
create index diet_logs_diet_meal_idx on public.diet_logs (diet_meal_id);
create index diet_logs_daily_meal_type_idx
  on public.diet_logs (daily_checkin_id, meal_type);

create table public.coach_feedback (
  feedback_id bigint generated by default as identity primary key,
  daily_checkin_id bigint not null references public.daily_checkins (daily_checkin_id),
  coach_id uuid not null references public.profiles (id),
  feedback_content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index coach_feedback_daily_checkin_idx
  on public.coach_feedback (daily_checkin_id);
create index coach_feedback_coach_idx on public.coach_feedback (coach_id);

-- Trigger helpers are kept outside exposed schemas.
create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
  for each row execute function private.set_updated_at();
create trigger exercises_set_updated_at before update on public.exercises
  for each row execute function private.set_updated_at();
create trigger workout_plans_set_updated_at before update on public.workout_plans
  for each row execute function private.set_updated_at();
create trigger workout_days_set_updated_at before update on public.workout_days
  for each row execute function private.set_updated_at();
create trigger workout_items_set_updated_at before update on public.workout_items
  for each row execute function private.set_updated_at();
create trigger diet_plans_set_updated_at before update on public.diet_plans
  for each row execute function private.set_updated_at();
create trigger diet_meals_set_updated_at before update on public.diet_meals
  for each row execute function private.set_updated_at();
create trigger daily_checkins_set_updated_at before update on public.daily_checkins
  for each row execute function private.set_updated_at();
create trigger workout_checkins_set_updated_at before update on public.workout_checkins
  for each row execute function private.set_updated_at();
create trigger diet_logs_set_updated_at before update on public.diet_logs
  for each row execute function private.set_updated_at();
create trigger coach_feedback_set_updated_at before update on public.coach_feedback
  for each row execute function private.set_updated_at();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_table_schema <> 'auth' or tg_table_name <> 'users' then
    raise exception 'handle_new_user may only run from auth.users';
  end if;

  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(
      coalesce(
        nullif(btrim(new.raw_user_meta_data ->> 'display_name'), ''),
        nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
        'User'
      ),
      80
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

-- RLS helper functions bypass relationship-table RLS without exposing table data.
create or replace function private.current_user_is_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.profiles p
      where p.id = (select auth.uid())
        and p.status = 'active'
    );
$$;

create or replace function private.current_user_has_role(expected_role public.user_role)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.profiles p
      where p.id = (select auth.uid())
        and p.role = expected_role
        and p.status = 'active'
    );
$$;

create or replace function private.is_active_coach_for(target_trainee uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.coach_trainees ct
      join public.profiles coach on coach.id = ct.coach_id
      join public.profiles trainee on trainee.id = ct.trainee_id
      where ct.coach_id = (select auth.uid())
        and ct.trainee_id = target_trainee
        and ct.status = 'active'
        and coach.role = 'coach'
        and coach.status = 'active'
        and trainee.role = 'trainee'
        and trainee.status = 'active'
    );
$$;

create or replace function private.is_active_coach_for_text(target_trainee text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.coach_trainees ct
      join public.profiles coach on coach.id = ct.coach_id
      join public.profiles trainee on trainee.id = ct.trainee_id
      where ct.coach_id = (select auth.uid())
        and ct.trainee_id::text = target_trainee
        and ct.status = 'active'
        and coach.role = 'coach'
        and coach.status = 'active'
        and trainee.role = 'trainee'
        and trainee.status = 'active'
    );
$$;

create or replace function private.is_active_relationship_with(target_user uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.coach_trainees ct
      join public.profiles coach on coach.id = ct.coach_id
      join public.profiles trainee on trainee.id = ct.trainee_id
      where ct.status = 'active'
        and coach.status = 'active'
        and trainee.status = 'active'
        and (
          (ct.coach_id = (select auth.uid()) and ct.trainee_id = target_user)
          or
          (ct.trainee_id = (select auth.uid()) and ct.coach_id = target_user)
        )
    );
$$;

create or replace function private.is_active_relationship_with_text(target_user text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.coach_trainees ct
      join public.profiles coach on coach.id = ct.coach_id
      join public.profiles trainee on trainee.id = ct.trainee_id
      where ct.status = 'active'
        and coach.status = 'active'
        and trainee.status = 'active'
        and (
          (ct.coach_id = (select auth.uid()) and ct.trainee_id::text = target_user)
          or
          (ct.trainee_id = (select auth.uid()) and ct.coach_id::text = target_user)
        )
    );
$$;

create or replace function private.mark_checkin_reviewed()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_trainee uuid;
begin
  select d.trainee_id
    into target_trainee
    from public.daily_checkins d
   where d.daily_checkin_id = new.daily_checkin_id;

  if (select auth.uid()) is not null
     and (
       new.coach_id <> (select auth.uid())
       or not private.is_active_coach_for(target_trainee)
     ) then
    raise exception 'coach is not authorized to review this check-in';
  end if;

  update public.daily_checkins
     set status = 'reviewed',
         reviewed_at = coalesce(reviewed_at, now())
   where daily_checkin_id = new.daily_checkin_id
     and status in ('submitted', 'reviewed');

  return new;
end;
$$;

create trigger coach_feedback_marks_checkin_reviewed
  after insert on public.coach_feedback
  for each row execute function private.mark_checkin_reviewed();

-- Enable RLS on every exposed business table.
alter table public.profiles enable row level security;
alter table public.coach_trainees enable row level security;
alter table public.exercises enable row level security;
alter table public.workout_plans enable row level security;
alter table public.workout_days enable row level security;
alter table public.workout_items enable row level security;
alter table public.diet_plans enable row level security;
alter table public.diet_meals enable row level security;
alter table public.daily_checkins enable row level security;
alter table public.workout_checkins enable row level security;
alter table public.diet_logs enable row level security;
alter table public.coach_feedback enable row level security;

create policy profiles_select_related
  on public.profiles for select to authenticated
  using (
    id = (select auth.uid())
    or private.is_active_relationship_with(id)
  );

create policy profiles_update_self
  on public.profiles for update to authenticated
  using (id = (select auth.uid()) and private.current_user_is_active())
  with check (id = (select auth.uid()) and private.current_user_is_active());

create policy coach_trainees_select_participant
  on public.coach_trainees for select to authenticated
  using (
    coach_id = (select auth.uid())
    or trainee_id = (select auth.uid())
  );

create policy exercises_select_active_or_owner
  on public.exercises for select to authenticated
  using (is_active or created_by = (select auth.uid()));

create policy exercises_insert_coach
  on public.exercises for insert to authenticated
  with check (
    created_by = (select auth.uid())
    and private.current_user_has_role('coach')
  );

create policy exercises_update_owner
  on public.exercises for update to authenticated
  using (
    created_by = (select auth.uid())
    and private.current_user_has_role('coach')
  )
  with check (
    created_by = (select auth.uid())
    and private.current_user_has_role('coach')
  );

create policy exercises_delete_owner
  on public.exercises for delete to authenticated
  using (
    created_by = (select auth.uid())
    and private.current_user_has_role('coach')
  );

create policy workout_plans_select_owner
  on public.workout_plans for select to authenticated
  using (
    coach_id = (select auth.uid())
    or (
      trainee_id = (select auth.uid())
      and status in ('published', 'archived')
    )
  );

create policy workout_plans_insert_assigned_coach
  on public.workout_plans for insert to authenticated
  with check (
    coach_id = (select auth.uid())
    and private.is_active_coach_for(trainee_id)
  );

create policy workout_plans_update_assigned_coach
  on public.workout_plans for update to authenticated
  using (
    coach_id = (select auth.uid())
    and private.is_active_coach_for(trainee_id)
  )
  with check (
    coach_id = (select auth.uid())
    and private.is_active_coach_for(trainee_id)
  );

create policy workout_plans_delete_assigned_coach
  on public.workout_plans for delete to authenticated
  using (
    coach_id = (select auth.uid())
    and private.is_active_coach_for(trainee_id)
  );

create policy workout_days_select_visible_plan
  on public.workout_days for select to authenticated
  using (
    exists (
      select 1 from public.workout_plans p
      where p.workout_plan_id = workout_days.workout_plan_id
    )
  );

create policy workout_days_insert_plan_coach
  on public.workout_days for insert to authenticated
  with check (
    exists (
      select 1 from public.workout_plans p
      where p.workout_plan_id = workout_days.workout_plan_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  );

create policy workout_days_update_plan_coach
  on public.workout_days for update to authenticated
  using (
    exists (
      select 1 from public.workout_plans p
      where p.workout_plan_id = workout_days.workout_plan_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  )
  with check (
    exists (
      select 1 from public.workout_plans p
      where p.workout_plan_id = workout_days.workout_plan_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  );

create policy workout_days_delete_plan_coach
  on public.workout_days for delete to authenticated
  using (
    exists (
      select 1 from public.workout_plans p
      where p.workout_plan_id = workout_days.workout_plan_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  );

create policy workout_items_select_visible_day
  on public.workout_items for select to authenticated
  using (
    exists (
      select 1 from public.workout_days d
      where d.workout_day_id = workout_items.workout_day_id
    )
    and exists (
      select 1 from public.exercises e
      where e.exercise_id = workout_items.exercise_id
    )
  );

create policy workout_items_insert_plan_coach
  on public.workout_items for insert to authenticated
  with check (
    exists (
      select 1
      from public.workout_days d
      join public.workout_plans p on p.workout_plan_id = d.workout_plan_id
      where d.workout_day_id = workout_items.workout_day_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
    and exists (
      select 1 from public.exercises e
      where e.exercise_id = workout_items.exercise_id
    )
  );

create policy workout_items_update_plan_coach
  on public.workout_items for update to authenticated
  using (
    exists (
      select 1
      from public.workout_days d
      join public.workout_plans p on p.workout_plan_id = d.workout_plan_id
      where d.workout_day_id = workout_items.workout_day_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  )
  with check (
    exists (
      select 1
      from public.workout_days d
      join public.workout_plans p on p.workout_plan_id = d.workout_plan_id
      where d.workout_day_id = workout_items.workout_day_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
    and exists (
      select 1 from public.exercises e
      where e.exercise_id = workout_items.exercise_id
    )
  );

create policy workout_items_delete_plan_coach
  on public.workout_items for delete to authenticated
  using (
    exists (
      select 1
      from public.workout_days d
      join public.workout_plans p on p.workout_plan_id = d.workout_plan_id
      where d.workout_day_id = workout_items.workout_day_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  );

create policy diet_plans_select_owner
  on public.diet_plans for select to authenticated
  using (
    coach_id = (select auth.uid())
    or (
      trainee_id = (select auth.uid())
      and status in ('published', 'archived')
    )
  );

create policy diet_plans_insert_assigned_coach
  on public.diet_plans for insert to authenticated
  with check (
    coach_id = (select auth.uid())
    and private.is_active_coach_for(trainee_id)
  );

create policy diet_plans_update_assigned_coach
  on public.diet_plans for update to authenticated
  using (
    coach_id = (select auth.uid())
    and private.is_active_coach_for(trainee_id)
  )
  with check (
    coach_id = (select auth.uid())
    and private.is_active_coach_for(trainee_id)
  );

create policy diet_plans_delete_assigned_coach
  on public.diet_plans for delete to authenticated
  using (
    coach_id = (select auth.uid())
    and private.is_active_coach_for(trainee_id)
  );

create policy diet_meals_select_visible_plan
  on public.diet_meals for select to authenticated
  using (
    exists (
      select 1 from public.diet_plans p
      where p.diet_plan_id = diet_meals.diet_plan_id
    )
  );

create policy diet_meals_insert_plan_coach
  on public.diet_meals for insert to authenticated
  with check (
    exists (
      select 1 from public.diet_plans p
      where p.diet_plan_id = diet_meals.diet_plan_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  );

create policy diet_meals_update_plan_coach
  on public.diet_meals for update to authenticated
  using (
    exists (
      select 1 from public.diet_plans p
      where p.diet_plan_id = diet_meals.diet_plan_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  )
  with check (
    exists (
      select 1 from public.diet_plans p
      where p.diet_plan_id = diet_meals.diet_plan_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  );

create policy diet_meals_delete_plan_coach
  on public.diet_meals for delete to authenticated
  using (
    exists (
      select 1 from public.diet_plans p
      where p.diet_plan_id = diet_meals.diet_plan_id
        and p.coach_id = (select auth.uid())
        and private.is_active_coach_for(p.trainee_id)
    )
  );

create policy daily_checkins_select_owner_or_coach
  on public.daily_checkins for select to authenticated
  using (
    trainee_id = (select auth.uid())
    or (
      status in ('submitted', 'reviewed')
      and private.is_active_coach_for(trainee_id)
    )
  );

create policy daily_checkins_insert_trainee
  on public.daily_checkins for insert to authenticated
  with check (
    trainee_id = (select auth.uid())
    and private.current_user_has_role('trainee')
    and status = 'draft'
  );

create policy daily_checkins_update_trainee_draft
  on public.daily_checkins for update to authenticated
  using (
    trainee_id = (select auth.uid())
    and status = 'draft'
    and private.current_user_has_role('trainee')
  )
  with check (
    trainee_id = (select auth.uid())
    and status in ('draft', 'submitted')
    and private.current_user_has_role('trainee')
  );

create policy daily_checkins_delete_trainee_draft
  on public.daily_checkins for delete to authenticated
  using (
    trainee_id = (select auth.uid())
    and status = 'draft'
    and private.current_user_has_role('trainee')
  );

create policy workout_checkins_select_visible_checkin
  on public.workout_checkins for select to authenticated
  using (
    exists (
      select 1 from public.daily_checkins d
      where d.daily_checkin_id = workout_checkins.daily_checkin_id
    )
  );

create policy workout_checkins_insert_trainee_draft
  on public.workout_checkins for insert to authenticated
  with check (
    exists (
      select 1
      from public.daily_checkins c
      join public.workout_days d on d.scheduled_date = c.checkin_date
      join public.workout_plans p on p.workout_plan_id = d.workout_plan_id
      where c.daily_checkin_id = workout_checkins.daily_checkin_id
        and d.workout_day_id = workout_checkins.workout_day_id
        and c.trainee_id = (select auth.uid())
        and c.status = 'draft'
        and p.trainee_id = (select auth.uid())
        and p.status in ('published', 'archived')
    )
  );

create policy workout_checkins_update_trainee_draft
  on public.workout_checkins for update to authenticated
  using (
    exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = workout_checkins.daily_checkin_id
        and c.trainee_id = (select auth.uid())
        and c.status = 'draft'
    )
  )
  with check (
    exists (
      select 1
      from public.daily_checkins c
      join public.workout_days d on d.scheduled_date = c.checkin_date
      join public.workout_plans p on p.workout_plan_id = d.workout_plan_id
      where c.daily_checkin_id = workout_checkins.daily_checkin_id
        and d.workout_day_id = workout_checkins.workout_day_id
        and c.trainee_id = (select auth.uid())
        and c.status = 'draft'
        and p.trainee_id = (select auth.uid())
        and p.status in ('published', 'archived')
    )
  );

create policy workout_checkins_delete_trainee_draft
  on public.workout_checkins for delete to authenticated
  using (
    exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = workout_checkins.daily_checkin_id
        and c.trainee_id = (select auth.uid())
        and c.status = 'draft'
    )
  );

create policy diet_logs_select_visible_checkin
  on public.diet_logs for select to authenticated
  using (
    exists (
      select 1 from public.daily_checkins d
      where d.daily_checkin_id = diet_logs.daily_checkin_id
    )
  );

create policy diet_logs_insert_trainee_draft
  on public.diet_logs for insert to authenticated
  with check (
    exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = diet_logs.daily_checkin_id
        and c.trainee_id = (select auth.uid())
        and c.status = 'draft'
    )
    and (
      diet_meal_id is null
      or exists (
        select 1
        from public.diet_meals m
        join public.diet_plans p on p.diet_plan_id = m.diet_plan_id
        join public.daily_checkins c on c.checkin_date = p.scheduled_date
        where m.diet_meal_id = diet_logs.diet_meal_id
          and c.daily_checkin_id = diet_logs.daily_checkin_id
          and p.trainee_id = (select auth.uid())
          and p.status in ('published', 'archived')
      )
    )
  );

create policy diet_logs_update_trainee_draft
  on public.diet_logs for update to authenticated
  using (
    exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = diet_logs.daily_checkin_id
        and c.trainee_id = (select auth.uid())
        and c.status = 'draft'
    )
  )
  with check (
    exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = diet_logs.daily_checkin_id
        and c.trainee_id = (select auth.uid())
        and c.status = 'draft'
    )
    and (
      diet_meal_id is null
      or exists (
        select 1
        from public.diet_meals m
        join public.diet_plans p on p.diet_plan_id = m.diet_plan_id
        join public.daily_checkins c on c.checkin_date = p.scheduled_date
        where m.diet_meal_id = diet_logs.diet_meal_id
          and c.daily_checkin_id = diet_logs.daily_checkin_id
          and p.trainee_id = (select auth.uid())
          and p.status in ('published', 'archived')
      )
    )
  );

create policy diet_logs_delete_trainee_draft
  on public.diet_logs for delete to authenticated
  using (
    exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = diet_logs.daily_checkin_id
        and c.trainee_id = (select auth.uid())
        and c.status = 'draft'
    )
  );

create policy coach_feedback_select_participant
  on public.coach_feedback for select to authenticated
  using (
    coach_id = (select auth.uid())
    or exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = coach_feedback.daily_checkin_id
        and c.trainee_id = (select auth.uid())
    )
  );

create policy coach_feedback_insert_assigned_coach
  on public.coach_feedback for insert to authenticated
  with check (
    coach_id = (select auth.uid())
    and exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = coach_feedback.daily_checkin_id
        and c.status in ('submitted', 'reviewed')
        and private.is_active_coach_for(c.trainee_id)
    )
  );

create policy coach_feedback_update_assigned_coach
  on public.coach_feedback for update to authenticated
  using (
    coach_id = (select auth.uid())
    and exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = coach_feedback.daily_checkin_id
        and private.is_active_coach_for(c.trainee_id)
    )
  )
  with check (
    coach_id = (select auth.uid())
    and exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = coach_feedback.daily_checkin_id
        and private.is_active_coach_for(c.trainee_id)
    )
  );

create policy coach_feedback_delete_assigned_coach
  on public.coach_feedback for delete to authenticated
  using (
    coach_id = (select auth.uid())
    and exists (
      select 1 from public.daily_checkins c
      where c.daily_checkin_id = coach_feedback.daily_checkin_id
        and private.is_active_coach_for(c.trainee_id)
    )
  );

-- New projects may not expose SQL-created tables automatically, so grant explicitly.
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;

grant select on public.profiles to authenticated;
grant update (display_name, avatar_path) on public.profiles to authenticated;
grant select on public.coach_trainees to authenticated;
grant select, insert, update, delete on public.exercises to authenticated;
grant select, insert, update, delete on public.workout_plans to authenticated;
grant select, insert, update, delete on public.workout_days to authenticated;
grant select, insert, update, delete on public.workout_items to authenticated;
grant select, insert, update, delete on public.diet_plans to authenticated;
grant select, insert, update, delete on public.diet_meals to authenticated;
grant select, insert, update, delete on public.daily_checkins to authenticated;
grant select, insert, update, delete on public.workout_checkins to authenticated;
grant select, insert, update, delete on public.diet_logs to authenticated;
grant select, insert, update, delete on public.coach_feedback to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on schema private from public, anon;
revoke all on all functions in schema private from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.current_user_is_active() to authenticated;
grant execute on function private.current_user_has_role(public.user_role) to authenticated;
grant execute on function private.is_active_coach_for(uuid) to authenticated;
grant execute on function private.is_active_coach_for_text(text) to authenticated;
grant execute on function private.is_active_relationship_with(uuid) to authenticated;
grant execute on function private.is_active_relationship_with_text(text) to authenticated;

-- Private Storage buckets. Database rows keep paths, not file bytes or public URLs.
insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', false),
  ('meal-photos', 'meal-photos', false);

create policy avatars_select_related
  on storage.objects for select to authenticated
  using (
    bucket_id = 'avatars'
    and (
      (storage.foldername(name))[1] = (select auth.uid())::text
      or private.is_active_relationship_with_text((storage.foldername(name))[1])
    )
  );

create policy avatars_insert_own_folder
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy avatars_update_own_folder
  on storage.objects for update to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy avatars_delete_own_folder
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy meal_photos_select_owner_or_coach
  on storage.objects for select to authenticated
  using (
    bucket_id = 'meal-photos'
    and (
      (storage.foldername(name))[1] = (select auth.uid())::text
      or private.is_active_coach_for_text((storage.foldername(name))[1])
    )
  );

create policy meal_photos_insert_own_folder
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'meal-photos'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy meal_photos_update_own_folder
  on storage.objects for update to authenticated
  using (
    bucket_id = 'meal-photos'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'meal-photos'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy meal_photos_delete_own_folder
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'meal-photos'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
