-- My Day can be enabled independently of the optional recovery schema.
-- This migration adds no sample records and is safe to rerun.
begin;

create table if not exists public.day_plans (
  day_plan_id bigint generated by default as identity primary key,
  trainee_id uuid not null references public.profiles (id) on delete cascade,
  plan_date date not null,
  available_minutes smallint not null check (available_minutes between 0 and 180),
  school_load text not null check (school_load in ('light', 'normal', 'heavy')),
  energy text not null check (energy in ('ready', 'tired', 'pain')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (trainee_id, plan_date)
);

alter table public.day_plans enable row level security;
revoke all on public.day_plans from public, anon, authenticated;
revoke all on sequence public.day_plans_day_plan_id_seq from public, anon, authenticated;
grant select on public.day_plans to authenticated;
grant insert (trainee_id, plan_date, available_minutes, school_load, energy) on public.day_plans to authenticated;
grant update (trainee_id, plan_date, available_minutes, school_load, energy) on public.day_plans to authenticated;
grant usage, select on sequence public.day_plans_day_plan_id_seq to authenticated;

-- Retire the earlier demo policies if that migration has already run.
drop policy if exists day_plans_select_own_or_coach on public.day_plans;
drop policy if exists day_plans_select_own on public.day_plans;
drop policy if exists day_plans_insert_own on public.day_plans;
drop policy if exists day_plans_update_own_draft on public.day_plans;
drop policy if exists day_plans_delete_own_draft on public.day_plans;

create policy day_plans_select_own on public.day_plans
  for select to authenticated
  using (trainee_id = (select auth.uid()) and (select private.current_user_has_role('trainee')));

create policy day_plans_insert_own on public.day_plans
  for insert to authenticated
  with check (
    trainee_id = (select auth.uid())
    and (select private.current_user_has_role('trainee'))
    and exists (
      select 1 from public.daily_checkins c
      where c.trainee_id = day_plans.trainee_id and c.checkin_date = day_plans.plan_date and c.status = 'draft'
    )
  );

create policy day_plans_update_own_draft on public.day_plans
  for update to authenticated
  using (trainee_id = (select auth.uid()) and (select private.current_user_has_role('trainee')))
  with check (
    trainee_id = (select auth.uid())
    and exists (
      select 1 from public.daily_checkins c
      where c.trainee_id = day_plans.trainee_id and c.checkin_date = day_plans.plan_date and c.status = 'draft'
    )
  );

create or replace function private.guard_day_plan_write()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  checkin_status public.daily_checkin_status;
begin
  if tg_op = 'UPDATE' and (new.trainee_id <> old.trainee_id or new.plan_date <> old.plan_date) then
    raise exception 'Daily priorities cannot be moved to another account or date.' using errcode = '23514';
  end if;

  -- Serialize saves with check-in submission so submitted dates stay read-only.
  select c.status into checkin_status from public.daily_checkins c
    where c.trainee_id = new.trainee_id and c.checkin_date = new.plan_date
    for update;
  if checkin_status is distinct from 'draft' then
    raise exception 'Your daily check-in has been submitted and is now read-only.' using errcode = '23514';
  end if;
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.guard_day_plan_write() from public, anon, authenticated;
drop trigger if exists day_plans_guard_write on public.day_plans;
create trigger day_plans_guard_write before insert or update on public.day_plans
  for each row execute function private.guard_day_plan_write();

notify pgrst, 'reload schema';
commit;
